// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:my_memories/global/flavor/app_flavor.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android();
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android() {
    if (AppFlavor.appFlavor == Flavor.female) {
      return FirebaseOptions(
        apiKey: 'AIzaSyAsjJMw9yF3ECRet7Bj1bi1TQxNwdiihAo',
        appId: '1:36759459071:android:968dda862b3afbef2828ca',
        messagingSenderId: '36759459071',
        projectId: 'mylikey-14625',
        storageBucket: 'mylikey-14625.appspot.com',
      );
    } else {
      return FirebaseOptions(
        apiKey: 'AIzaSyAsjJMw9yF3ECRet7Bj1bi1TQxNwdiihAo',
        appId: '1:36759459071:android:59a18ec6cf77d51a2828ca',
        messagingSenderId: '36759459071',
        projectId: 'mylikey-14625',
        storageBucket: 'mylikey-14625.appspot.com',
      );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlmiCeWYmDjfeH9Ttf5uKjElHMOdWV0FI',
    appId: '1:36759459071:ios:27aff5cffbdabf4f2828ca',
    messagingSenderId: '36759459071',
    projectId: 'mylikey-14625',
    storageBucket: 'mylikey-14625.appspot.com',
    iosBundleId: 'xuuan.my.memories.myMemories',
  );
}
